### ISSUE TITLE
Problem: upgrade integration tests fails in recent version

### ISSUE THREAD

**Issue by yihuang** [crypto-com/chain-main#300]
**Describe the bug**
It fails to startup after restart for upgrade:

```
I[2020-12-19|09:00:14.897] applying upgrade "upgrade-test" at height: 17 module=main 
I[2020-12-19|09:00:14.898] minted 25993basecro from mint module account module=x/bank 
panic: Validator consensus-address crocnclcons15ytsvefydka7y0txlr9vxlm0q4djgngrupg5tz not found

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/slashing/keeper.Keeper.HandleValidatorSignature(0x58ed220, 0xc00122c510, 0xc4b2e58, 0xc00117e650, 0x5916b60, 0xc0001fa300, 0x590c9a0, 0xc00059da40, 0x5908aa0, 0xc000048200, ...)
	/private/tmp/nix-build-chain-maind-0.0.1.drv-1/src/vendor/github.com/cosmos/cosmos-sdk/x/slashing/keeper/infractions.go:20 +0x1e25
github.com/cosmos/cosmos-sdk/x/slashing.BeginBlocker(0x5908aa0, 0xc000048200, 0x591b600, 0xc000247a80, 0xb, 0x0, 0xc000fbd110, 0x9, 0x11, 0x3360dcd0, ...)
	/private/tmp/nix-build-chain-maind-0.0.1.drv-1/src/vendor/github.com/cosmos/cosmos-sdk/x/slashing/abci.go:23 +0x287
github.com/cosmos/cosmos-sdk/x/slashing.AppModule.BeginBlock(...)
	/private/tmp/nix-build-chain-maind-0.0.1.drv-1/src/vendor/github.com/cosmos/cosmos-sdk/x/slashing/module.go:164
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(0xc000fdaa80, 0x5908aa0, 0xc000048200, 0x591b600, 0xc000247a80, 0xb, 0x0, 0xc000fbd110, 0x9, 0x11, ...)
	/private/tmp/nix-build-chain-maind-0.0.1.drv-1/src/vendor/github.com/cosmos/cosmos-sdk/types/module/module.go:339 +0x1a2
github.com/crypto-com/chain-main/app.(*ChainApp).BeginBlocker(...)
	/private/tmp/nix-build-chain-maind-0.0.1.drv-1/src/app/app.go:364
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(0xc00059bd40, 0xc0012b3160, 0x20, 0x20, 0xb, 0x0, 0xc000fbd110, 0x9, 0x11, 0x3360dcd0, ...)
	/private/tmp/nix-build-chain-maind-0.0.1.drv-1/src/vendor/github.com/cosmos/cosmos-sdk/baseapp/abci.go:179 +0x658
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(0xc00078f020, 0xc0012b3160, 0x20, 0x20, 0xb, 0x0, 0xc000fbd110, 0x9, 0x11, 0x3360dcd0, ...)
	/private/tmp/nix-build-chain-maind-0.0.1.drv-1/src/vendor/github.com/tendermint/tendermint/abci/client/local_client.go:274 +0xfa
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(0xc00122cd80, 0xc0012b3160, 0x20, 0x20, 0xb, 0x0, 0xc000fbd110, 0x9, 0x11, 0x3360dcd0, ...)
	/private/tmp/nix-build-chain-maind-0.0.1.drv-1/src/vendor/github.com/tendermint/tendermint/proxy/app_conn.go:81 +0x75
github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x5908f20, 0xc0005a45e0, 0x5914280, 0xc00122cd80, 0xc00000c1e0, 0x591b880, 0xc00122c870, 0x1, 0x63d7a50, 0x0, ...)
	/private/tmp/nix-build-chain-maind-0.0.1.drv-1/src/vendor/github.com/tendermint/tendermint/state/execution.go:301 +0x37b
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc000fdb650, 0xb, 0x0, 0x0, 0x0, 0xc000fbcb70, 0x9, 0x1, 0x10, 0xc000fc0600, ...)
	/private/tmp/nix-build-chain-maind-0.0.1.drv-1/src/vendor/github.com/tendermint/tendermint/state/execution.go:139 +0x265
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(0xc000d9c748, 0xb, 0x0, 0x0, 0x0, 0xc000fbcb70, 0x9, 0x1, 0x10, 0xc000fc0600, ...)
	/private/tmp/nix-build-chain-maind-0.0.1.drv-1/src/vendor/github.com/tendermint/tendermint/consensus/replay.go:503 +0x268
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc0005ca748, 0xb, 0x0, 0x0, 0x0, 0xc000fbcb70, 0x9, 0x1, 0x10, 0xc000fc0600, ...)
	/private/tmp/nix-build-chain-maind-0.0.1.drv-1/src/vendor/github.com/tendermint/tendermint/consensus/replay.go:416 +0xd18
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000d9c748, 0x591f2a0, 0xc000694680, 0xc000691a10, 0x203000)
	/private/tmp/nix-build-chain-maind-0.0.1.drv-1/src/vendor/github.com/tendermint/tendermint/consensus/replay.go:268 +0x4d8
github.com/tendermint/tendermint/node.doHandshake(0x591b880, 0xc00122c870, 0xb, 0x0, 0x0, 0x0, 0xc000fbcb70, 0x9, 0x1, 0x10, ...)
	/private/tmp/nix-build-chain-maind-0.0.1.drv-1/src/vendor/github.com/tendermint/tendermint/node/node.go:277 +0x1d8
github.com/tendermint/tendermint/node.NewNode(0xc000f87180, 0x59006e0, 0xc000fbf720, 0xc00122d4e0, 0x58d3640, 0xc00000e8e0, 0xc00122d560, 0x5749c08, 0xc00122d690, 0x5908f20, ...)
	/private/tmp/nix-build-chain-maind-0.0.1.drv-1/src/vendor/github.com/tendermint/tendermint/node/node.go:685 +0x1da5
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc0011b63c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5908c60, 0xc0010a5aa0, ...)
	/private/tmp/nix-build-chain-maind-0.0.1.drv-1/src/vendor/github.com/cosmos/cosmos-sdk/server/start.go:216 +0x578
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc001165b80, 0xc0011b64e0, 0x0, 0x2, 0x0, 0x0)
	/private/tmp/nix-build-chain-maind-0.0.1.drv-1/src/vendor/github.com/cosmos/cosmos-sdk/server/start.go:117 +0x154
github.com/spf13/cobra.(*Command).execute(0xc001165b80, 0xc0011b64c0, 0x2, 0x2, 0xc001165b80, 0xc0011b64c0)
	/private/tmp/nix-build-chain-maind-0.0.1.drv-1/src/vendor/github.com/spf13/cobra/command.go:850 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc001020840, 0x0, 0x0, 0xc0011b4480)
	/private/tmp/nix-build-chain-maind-0.0.1.drv-1/src/vendor/github.com/spf13/cobra/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/nix-build-chain-maind-0.0.1.drv-1/src/vendor/github.com/spf13/cobra/command.go:895
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/private/tmp/nix-build-chain-maind-0.0.1.drv-1/src/vendor/github.com/spf13/cobra/command.go:888
github.com/crypto-com/chain-main/cmd/chain-maind/app.Execute(0xc001020840, 0x5913da0, 0xc00109bae0)
	/private/tmp/nix-build-chain-maind-0.0.1.drv-1/src/cmd/chain-maind/app/app.go:91 +0x175
main.main()
	/private/tmp/nix-build-chain-maind-0.0.1.drv-1/src/cmd/chain-maind/main.go:12 +0x2a
```

**To Reproduce**
- remove the skip mark on `test_manual_upgrade`
- run: 
  ```
  $ pytest -s -k test_manual_upgrade
  ```

**Comment by tomtau** [comment]
resolved in https://github.com/crypto-com/chain-main/commit/15bbf25582f52ca7d21e505da901a0a8c91c18a3
